/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formlar;

import DBCRUD.PostgreSQL.tblmusteri;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author vektorel
 */
   
        
public class frmMNusteri extends javax.swing.JFrame {
  DBCRUD.PostgreSQL.tblmusteri mst = new tblmusteri();
 Modeller.tblmusteri musteri;
  /** Creates new form frmMNusteri */
    public frmMNusteri() {
        initComponents();
        tabloDoldur();
        
           }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Duzenle = new javax.swing.JMenuItem();
        Sil = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtkimlik = new javax.swing.JTextField();
        txtad = new javax.swing.JTextField();
        txtsoyad = new javax.swing.JTextField();
        cmbCinsiyet = new javax.swing.JComboBox<>();
        txtdogumtarihi = new javax.swing.JFormattedTextField();
        txtceptel = new javax.swing.JFormattedTextField();
        txtyakintel = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtsaglikdurumu = new javax.swing.JTextPane();
        btnYeniKayit = new javax.swing.JButton();
        btnKaydet = new javax.swing.JButton();
        btnDuzenle = new javax.swing.JButton();
        btnIptal = new javax.swing.JButton();
        btnCikis = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        Duzenle.setText("Düzenle");
        Duzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuzenleActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Duzenle);

        Sil.setText("Sil");
        jPopupMenu1.add(Sil);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("TC Kimlik");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel2.setText("Ad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setText("Soyad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setText("Cinsiyet");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel5.setText("Doğum Tarihi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel6.setText("Cep Telefonu");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setText("Yakın Ceptel");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel8.setText("Sağlık Durumu");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\vektorel\\Desktop\\peoplefsdfdfsdf.png")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 120, 130));

        txtkimlik.setEditable(false);
        txtkimlik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkimlikKeyPressed(evt);
            }
        });
        getContentPane().add(txtkimlik, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 90, -1));

        txtad.setEditable(false);
        getContentPane().add(txtad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 180, -1));

        txtsoyad.setEditable(false);
        getContentPane().add(txtsoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 180, -1));

        cmbCinsiyet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Erkek", "Kadın", "Diğer" }));
        getContentPane().add(cmbCinsiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 90, -1));

        txtdogumtarihi.setEditable(false);
        try {
            txtdogumtarihi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtdogumtarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 110, -1));

        txtceptel.setEditable(false);
        try {
            txtceptel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtceptel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 110, -1));

        txtyakintel.setEditable(false);
        try {
            txtyakintel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtyakintel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 110, -1));

        txtsaglikdurumu.setEditable(false);
        jScrollPane1.setViewportView(txtsaglikdurumu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 350, 70));

        btnYeniKayit.setText("Yeni Kayıt");
        btnYeniKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeniKayitActionPerformed(evt);
            }
        });
        getContentPane().add(btnYeniKayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        btnKaydet.setText("Kaydet");
        btnKaydet.setEnabled(false);
        btnKaydet.setPreferredSize(new java.awt.Dimension(81, 23));
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });
        getContentPane().add(btnKaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        btnDuzenle.setText("Güncelle");
        btnDuzenle.setEnabled(false);
        btnDuzenle.setPreferredSize(new java.awt.Dimension(81, 23));
        btnDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuzenleActionPerformed(evt);
            }
        });
        getContentPane().add(btnDuzenle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        btnIptal.setText("İptal");
        btnIptal.setEnabled(false);
        btnIptal.setPreferredSize(new java.awt.Dimension(81, 23));
        btnIptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIptalActionPerformed(evt);
            }
        });
        getContentPane().add(btnIptal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        btnCikis.setText("Çıkış");
        btnCikis.setPreferredSize(new java.awt.Dimension(81, 23));
        getContentPane().add(btnCikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setToolTipText("");
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 460, 350));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("X");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkimlikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkimlikKeyPressed
       int uzunluk = txtkimlik.getText().length();
       if(uzunluk>=11){
       txtkimlik.setText(txtkimlik.getText().substring(0,10));
       }
    }//GEN-LAST:event_txtkimlikKeyPressed

    private void btnYeniKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeniKayitActionPerformed
       btnAcYeniKayit();
    }//GEN-LAST:event_btnYeniKayitActionPerformed

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        btnKapatKaydet();
        Kaydet();
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void btnIptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIptalActionPerformed
        btnKapatKaydet();
    }//GEN-LAST:event_btnIptalActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
        
        System.out.println("ilk id....:"+ jTable1.getModel().getValueAt(0, 4));
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void DuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuzenleActionPerformed
      int id;
      id = (int)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4);
      AcDuzenle(id);
    }//GEN-LAST:event_DuzenleActionPerformed

    private void btnDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuzenleActionPerformed
       Guncelle();
    }//GEN-LAST:event_btnDuzenleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMNusteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMNusteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMNusteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMNusteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMNusteri().setVisible(true);
            }
        });
    }

    public void btnAcYeniKayit(){
    
        btnYeniKayit.setEnabled(false);
        btnKaydet.setEnabled(true);
        btnIptal.setEnabled(true);
        
       txtad.setEditable(true);
       txtceptel.setEditable(true);
       txtdogumtarihi.setEditable(true);
       txtkimlik.setEditable(true);
       txtsaglikdurumu.setEditable(true);
       txtsoyad.setEditable(true);
       txtyakintel.setEditable(true);
       cmbCinsiyet.setEditable(true);
        
                
    }
    
    public void btnKapatKaydet(){
        btnIptal.setEnabled(false);
        btnKaydet.setEnabled(false);
        btnYeniKayit.setEnabled(true);
       txtad.setEditable(false);
       txtceptel.setEditable(false);
       txtdogumtarihi.setEditable(false);
       txtkimlik.setEditable(false);
       txtsaglikdurumu.setEditable(false);
       txtsoyad.setEditable(false);
       txtyakintel.setEditable(false);
       cmbCinsiyet.setEditable(false);
        
    }
    
    public void btnAcDuzenle(){
    
        btnYeniKayit.setEnabled(false);
        btnKaydet.setEnabled(false);
        btnIptal.setEnabled(true);
        btnDuzenle.setEnabled(true);
       txtad.setEditable(true);
       txtceptel.setEditable(true);
       txtdogumtarihi.setEditable(true);
       txtkimlik.setEditable(true);
       txtsaglikdurumu.setEditable(true);
       txtsoyad.setEditable(true);
       txtyakintel.setEditable(true);
       cmbCinsiyet.setEditable(true);
    }
    
    public void tabloDoldur(){
         Object[][] data = new Object[mst.Listele().size()][5];
            
            for(int i = 0; i < mst.Listele().size(); i++) {
                
                data[i][0] = ((Modeller.tblmusteri) mst.Listele().get(i)).getAd();
                data[i][1] = ((Modeller.tblmusteri) mst.Listele().get(i)).getSoyad();
                data[i][2] = ((Modeller.tblmusteri) mst.Listele().get(i)).getTckimlik();
                data[i][3] = ((Modeller.tblmusteri) mst.Listele().get(i)).getCeptel();
                data[i][4] = ((Modeller.tblmusteri) mst.Listele().get(i)).getId();
              
            }
            
            TableModel model = new DefaultTableModel(data, 
                    new Object[]{"Ad", "Soyad", "TC Kimlik", "Cep Telefonu","Id"});
           
            jTable1.setModel(model);
            jTable1.getColumnModel().getColumn(4).setMinWidth(0);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(4).setWidth(0);
    }
    
    public void Kaydet(){
     musteri = new Modeller.tblmusteri();
     musteri.setAd(txtad.getText());
     musteri.setCeptel(txtceptel.getText());
     musteri.setCinsiyet(cmbCinsiyet.getSelectedItem().toString());
    // musteri.setDogumtarihi(Date.from(LocalDate.parse(txtdogumtarihi.getText(), DateTimeFormatter.ofPattern("dd-MM-yyyy")).atStartOfDay().toInstant(ZoneOffset.UTC)));
     musteri.setSaglikdurumu(txtsaglikdurumu.getText());
     musteri.setSoyad(txtsoyad.getText());
     musteri.setTckimlik(txtkimlik.getText());
     musteri.setYakintel(txtyakintel.getText());
     mst.Kaydet(musteri);
     tabloDoldur();
     
    }
    
    public void AcDuzenle(int id){
     btnAcDuzenle();
     musteri = (Modeller.tblmusteri)mst.Bul(id);
    
     System.out.println("id..:"+ musteri.getId());
     txtad.setText(musteri.getAd());
     txtceptel.setText(musteri.getCeptel());
     //txtdogumtarihi.setText(musteri.getDogumtarihi().toString());
     txtkimlik.setText(musteri.getTckimlik());
     txtsaglikdurumu.setText(musteri.getSaglikdurumu());
     txtsoyad.setText(musteri.getSoyad());
     txtyakintel.setText(musteri.getYakintel());
                 
        
    }
    
    public void Guncelle(){
   
     musteri.setAd(txtad.getText());
     musteri.setCeptel(txtceptel.getText());
     musteri.setCinsiyet(cmbCinsiyet.getSelectedItem().toString());
    // musteri.setDogumtarihi(Date.from(LocalDate.parse(txtdogumtarihi.getText(), DateTimeFormatter.ofPattern("dd-MM-yyyy")).atStartOfDay().toInstant(ZoneOffset.UTC)));
     musteri.setSaglikdurumu(txtsaglikdurumu.getText());
     musteri.setSoyad(txtsoyad.getText());
     musteri.setTckimlik(txtkimlik.getText());
     musteri.setYakintel(txtyakintel.getText());
     mst.Duzenle(musteri);
             
     tabloDoldur();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Duzenle;
    private javax.swing.JMenuItem Sil;
    private javax.swing.JButton btnCikis;
    private javax.swing.JButton btnDuzenle;
    private javax.swing.JButton btnIptal;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnYeniKayit;
    private javax.swing.JComboBox<String> cmbCinsiyet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtad;
    private javax.swing.JFormattedTextField txtceptel;
    private javax.swing.JFormattedTextField txtdogumtarihi;
    private javax.swing.JTextField txtkimlik;
    private javax.swing.JTextPane txtsaglikdurumu;
    private javax.swing.JTextField txtsoyad;
    private javax.swing.JFormattedTextField txtyakintel;
    // End of variables declaration//GEN-END:variables

}
